spring:
  application:
    name: gateway
  cloud:
    gateway:
      # 开启项目名映射功能，即通过服务名访问项目，不需要写明具体IP地址
      discovery:
        locator:
          enabled: false
          # 请求路径去不转为小写字母，如AA/aB转为aa/ab
#          lower-case-service-id: true
      routes:
        #路由的id,没有规定但必须是唯一的，最好对应相应的微服务名
        - id: user-service
#          uri: http://localhost:8011
          uri: lb://user-service
          # 断言,如果路径里带有/git
          # 比如localhost:8080/git  那么地址会被转为 https://github.com/ 但浏览器显示的地址还是localhost:8080/git
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
        - id: mq-service
          #  uri: http://localhost:8011
          uri: lb://mq-service
          # 断言,如果路径里带有/git
          # 比如localhost:8080/git  那么地址会被转为 https://github.com/ 但浏览器显示的地址还是localhost:8080/git
          predicates:
            - Path=/mq-service/**
          filters:
            - StripPrefix=1
  datasource:
    url: jdbc:mysql://localhost:3306/mite_tb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/