spring:
  application:
    name: swagger
server:
  port: 8088
eureka:
  client:
    serviceUrl:
      ###当前服务注册到eureka服务
      defaultZone: http://localhost:8761/eureka
    ###需要将自身的服务注册到eureka上面去
    register-with-eureka: true
    ###需要检索服务
    fetch-registry: true
swagger:
  enabled: true